export PATH="$PNPM_HOME:$PATH"
# All paths loaded into the environment lie here
export PATH="$PATH:$ANDROID_HOME/tools"
export PATH="$PATH:$ANDROID_HOME/tools/bin"
export PATH="$PATH:$ANDROID_HOME/emulator"
export PATH="$PATH:$ANDROID_HOME/platform-tools"
export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/Programs/v/"
export PATH="$PATH:$HOME/Documents/system-scripts"
export PATH="$PATH:$VOLTA_HOME/bin"
export PATH="$PATH:$HOME/.pub-cache/bin"
export PATH="$PATH:$HOME/Programs/istio/bin"
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
