# All paths loaded into the environment lie here
export PATH="$PATH:$ANDROID_HOME/tools"
export PATH="$PATH:$ANDROID_HOME/tools/bin"
export PATH="$PATH:$ANDROID_HOME/emulator"
export PATH="$PATH:$ANDROID_HOME/platform-tools"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/bin"
export PATH="$PATH":"$HOME/.pub-cache/bin"
export PATH="$PATH":"$HOME/Programs/v/"
export PATH="$PATH":"/run/media/drives/documentSSD/main/Scripts"
export PATH="$PATH:$VOLTA_HOME/bin"
export PATH="$PNPM_HOME:$PATH"
export PATH="$HOME/Programs/istio/bin:$PATH"
